### ISSUE TITLE
Humidity value is fixed

### ISSUE THREAD

**Issue by restelrich** [relayr/relayr-firmware-nrf51-modules#1]
I tried with 4 different sensors at the moment and none of them change humidity values when changing their "environmental variables" (a.k.a. breathing onto the sensor).

**Comment by restelrich** [comment]
When registering a sensor service in:
simble_srv_init(ctx, simble_get_vendor_uuid_class(), VENDOR_UUID_SENSOR_SERVICE)

we cannot register more than one sensor service for the same module, since the UUID for all of them would be the same.

In the TEMP/RH sensor, since there are two sensor services, the last service registered was the only one  available for callbacks.

A new UUID for the TEMP sensor service has been introduce to fix the issue.

**Comment by tralamazza** [comment]
closed by https://github.com/relayr/relayr-firmware-nrf51-modules/commit/1c8c00385e100b5e2d2955f1bbfa32dd26efdf6a
